# Generated by Django 3.1.3 on 2020-11-28 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_tasklist_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklist",
            name="description",
        ),
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default=datetime.date(2020, 11, 28)),
        ),
    ]
