# Generated by Django 3.1.3 on 2020-11-28 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20201128_2002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2020, 11, 28, 20, 3, 15, 782619, tzinfo=utc)
            ),
        ),
    ]
