# Generated by Django 3.1.3 on 2020-11-28 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20201128_2003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
